version: '2'

services:

  tailz:
    image: tailscale/tailscale
    command: ["/bin/sh", "-c", "/tailz/tailnet.sh"]
    depends_on:
      - secretz
    restart: "unless-stopped"
    environment:
      - D_EXTRA_ARGS=--outbound-http-proxy-listen=0.0.0.0:1055
      - STATE=/tailz/tailscale.state
    volumes:
      - tailz:/tailz

  secretz:
    build: .
    restart: "no"
    environment:
      - VAULT_API_ADDR=https://secretz.claude.2w.design
      - VAULT_ADDR=https://secretz.claude.2w.design
      - HTTPS_PROXY=http://tailz:1055
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/vault/file
      - secretz:/vault/config
      - tailz:/tailZ
      - secretz:/secretZ
    labels:
      traefik.enable: true

  configz:
    build: .
    entrypoint: ["/configZ/entry.sh"]
    depends_on:
      - secretz
    restart: "no"
    environment:
      - VAULT_API_ADDR=http://secretz:8200
      - VAULT_ADDR=http://secretz:8200
    volumes:
      - proxz:/proxZ
      - code:/codeZ
      - backupz:/backupZ


  proxz:
    image: traefik:2.5
    depends_on:
      - configz
    restart: "no"
    ports:
      - 80:80 
      - 443:443
    environment:
      - CF_DNS_API_TOKEN_FILE=/etc/traefik/CF_DNS_API_TOKEN
    volumes:
      - proxz:/etc/traefik:ro
      - certz:/etc/certz
    labels:
      io.balena.features.balena-socket: '1'
      traefik.enable: true
      traefik.http.routers.api.service: 'api@internal'

  backupz:
    image: azinchen/duplicacy:latest
    depends_on:
      - configz
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
      - RUN_JOB_IMMEDIATELY=false
      - BACKUP_CRON=0 1 * * *
    volumes:
      - backupz:/config
      - vault:/data/vault
      - unifi:/data/unifi
      - uisp3:/data/uisp
      - hass:/data/hass
      - esp:/data/esp
      - grafana:/data/grafana

  restore:
    image: saspus/duplicacy-web:latest
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
      - GRP_ID=3875
      - USR_ID=3875
    volumes:
      - restore:/config
    labels:
      traefik.enable: true
      traefik.http.services.restore.loadbalancer.server.port: 3875

  hass-config:
    image: causticlab/hass-configurator-docker:arm
    restart: "no"
    environment:
      - HC_BASEPATH=/hass-config
    volumes:
      - hass:/hass-config
    labels:
      traefik.enable: true
      traefik.http.services.hass-config.loadbalancer.server.port: 3218

  hass:
    image: homeassistant/raspberrypi4-homeassistant
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/*:/dev/*
    volumes:
      - hass:/config
    labels:
      traefik.enable: true
      traefik.http.services.hass.loadbalancer.server.port: 8123

  esp:
    image: esphome/esphome
    command: ["-q", "dashboard", "/config"]
    restart: unless-stopped
    environment:
      - "ESPHOME_DASHBOARD_USE_PING=true"
    volumes:
      - esp:/config
    labels:
      traefik.enable: 'true'
      traefik.http.services.esp.loadbalancer.server.port: '6052'


  unifi:
    build: ./unifi
    restart: unless-stopped
#    user: 8000:0
    ports:
      - 8080:8080
      - 3478:3478/udp
      - 10001:10001/udp
      - 6789:6789
      - 5514:5514/udp
    volumes:
      - unifi:/usr/lib/unifi/data
      - unifi-log:/usr/lib/unifi/logs
    labels:
      traefik.enable: true
      traefik.http.services.unifi.loadbalancer.server.port: 8000

  uisp:
    image: nico640/docker-unms:1.4.2
    restart: unless-stopped
    ports:
      - 7443:443
      - 2055:2055/udp
    environment:
      - TZ=Australia/Sydney
      - QUIET_MODE=1
    volumes:
      - uisp3:/config
    labels:
      traefik.enable: true
      traefik.http.services.unms.loadbalancer.server.port: 443
      traefik.http.services.unms.loadbalancer.server.scheme: https

  loki:
    image: grafana/loki:2.4.1
    command: ["-config.file=/etc/loki/local-config.yaml"]
    restart: unless-stopped
    ports:
      - 3100:3100
    environment:
      - TZ=Australia/Sydney
    volumes:
      - loki:/loki

  dash:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
    volumes:
      - grafana:/var/lib/grafana
    labels:
      traefik.enable: true

volumes:
  tailz:
  vault:
  secretz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  certz:
  proxz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  backupz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  restore:
  code:
  hass: 
  esp:
  unifi:
  unifi-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  uisp3:
  loki:
  grafana:
