version: '3'

services:

  proxz:
    image: traefik:2.8
    restart: unless-stopped
    ports:
      - 80:80 
      - 443:443
    environment:
      - TRAEFIK_API=true
      - TRAEFIK_CERTIFICATESRESOLVERS_<NAME>_ACME_DNSCHALLENGE_PROVIDER
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_api_token
    secrets: 
      - cloudflare_api_token
    volumes:
      - proxz:/etc/traefik:ro
      - certz:/etc/certz
    labels:
      traefik.enable: true
      traefik.http.routers.api.service: 'api@internal'

volumes:
  certz:
  proxz:
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  cloudflare_api_token:
    external: true
