version: '2'

services:

  configz:
    build: .
    restart: always
    environment:
      - VAULT_ADDR=http://secretz:8200
    volumes:
      - oci:/root/.oci
      - logz:/logZ
      - proxz:/proxZ
      - secretz:/secretZ
      - backupz:/backupZ

#  devz:
#    build: .
#    restart: always
#    entrypoint: ["sh", "-c", "sh"]
#    labels:
#      - "traefik.enable=true"

  proxz:
    image: traefik:2.3
    depends_on:
      - secretz
    restart: always
    ports:
      - 80:80 
      - 443:443
    environment:
      - CF_DNS_API_TOKEN_FILE=/etc/traefik/CF_DNS_API_TOKEN
    volumes:
      - proxz:/etc/traefik:ro
      - certz:/etc/certz
    labels:
      io.balena.features.balena-socket: '1'
      traefik.enable: true
      traefik.http.routers.api.service: 'api@internal'

  logz:
    image: fluent/fluent-bit:1.6
    depends_on:
      - secretz
    restart: always 
    entrypoint: ["/logz/entry.sh"]
    volumes:
      - logz:/logz:ro
    labels:
      io.balena.features.supervisor-api: '1'

  secretz:
    image: vault:1.6.1
    depends_on:
      - configz
    restart: always
    command: ["server"]
    environment:
      - VAULT_ADDR=http://secretz:8200
      - VAULT_API_ADDR=http://secretz:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - oci:/home/vault/.oci:ro
      - vault:/vault/file
      - secretz:/vault/config
    labels:
      traefik.enable: true

  unifi:
    build: ./unifi
    restart: no
#    user: 8000:0
    ports:
      - 8080:8080
      - 3478:3478/udp
      - 10001:10001/udp
      - 6789:6789
      - 5514:5514/udp
    volumes:
      - unifi:/usr/lib/unifi/data
      - unifi-log:/usr/lib/unifi/logs
    labels:
      traefik.enable: true
      traefik.http.services.unifi.loadbalancer.server.port: 8000

  unms:
    image: nico640/docker-unms:1.2.7
    restart: always
    ports:
      - 7443:443
      - 2055:2055/udp
    environment:
      - TZ=Australia/Sydney
      - QUIET_MODE=1
    volumes:
      - unms:/config
    labels:
      traefik.enable: true
      traefik.http.services.unms.loadbalancer.server.port: 443
      traefik.http.services.unms.loadbalancer.server.scheme: https


  homebridge:
    image: oznu/homebridge:3.3.0
    restart: always
    network_mode: host
    environment:
      - TZ=Australia/Sydney
      - PACKAGES=python3-dev,py3-pip
      - PGID=8888
      - PUID=8888
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8888
    volumes:
      - homebridge:/homebridge

  backupz:
    image: azinchen/duplicacy:latest
    depends_on:
      - configz
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
      - RUN_JOB_IMMEDIATELY=false
      - BACKUP_CRON=0 1 * * *
    volumes:
      - backupz:/config
      - vault:/data/vault
      - unifi:/data/unifi
      - unms:/data/unms

  restore:
    image: saspus/duplicacy-web:latest
    environment:
      - TZ=Australia/Sydney
      - GRP_ID=3875
      - USR_ID=3875
    volumes:
      - restore:/config
    labels:
      traefik.enable: true
      traefik.http.services.restore.loadbalancer.server.port: 3875
  
  codex:
    image: ghcr.io/linuxserver/code-server
    environment:
      - PUID=3333
      - PGID=3333
      - TZ=Australia/Sydney
#      - PASSWORD=yourpass
      - SUDO_PASSWORD_HASH=$5$6ufiwWdL8bYJNcIZ$XsBQZadk0gklKJQKm1.D3fg3PgUZXYam9EE3Q4/Jap8
    volumes:
      - codex:/config
    labels:
      traefik.enable: true
      traefik.http.services.codex.loadbalancer.server.port: 8443

volumes:
  oci:
  vault:
  secretz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  certz:
  proxz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  logz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  unifi:
  unifi-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  unms:
  homebridge:
  restore:
  backupz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  codex:

