version: '3.8'

services:

#  tailz:
#    image: tailscale/tailscale:v1.34
#    command: /bin/sh -c "TS_AUTH_KEY=$$(cat /run/secrets/tailscale_auth_key) /usr/local/bin/containerboot"
#    environment:
#      - TZ=$TZ
#      - TS_OUTBOUND_HTTP_PROXY_LISTEN=:1055
#      - TS_STATE_DIR=/tailz/
#    secrets: 
#      - tailscale_auth_key
#    volumes:
#      - tailz:/tailz

  proxz:
    image: traefik:2.9
    ports:
      - target: 443
        published: 443 
        mode: host
    environment:
      - TZ=$TZ
      - TRAEFIK_API=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_http_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_http_HTTP_REDIRECTIONS_ENTRYPOINT_TO=https
      - TRAEFIK_ENTRYPOINTS_https_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_https_HTTP_TLS_CERTRESOLVER=letsencrypt
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_STORAGE=/etc/certz/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_DNSCHALLENGE_PROVIDER=cloudflare
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_DNSCHALLENGE_RESOLVERS=1.1.1.1:53
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE=Host(`{{ `{{ index .Labels "com.docker.swarm.service.name" | splitList "_" | last }}` }}.$domain`)
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL=$email
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_api_token
    secrets: 
      - cloudflare_api_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certz:/etc/certz
    labels:
      traefik.enable: 'true'
      traefik.http.routers.api.service: 'api@internal'

  restore:
    image: saspus/duplicacy-web:latest
    environment:
      - TZ=$TZ
      - GRP_ID=3875
      - USR_ID=3875
    volumes:
      - restore:/config
    labels:
      traefik.enable: 'true'
      traefik.http.services.restore.loadbalancer.server.port: 3875

  esp:
    image: esphome/esphome:2022.12
    command: ["-q", "dashboard", "/config"]
    environment:
      - TZ=$TZ
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - esp:/config
    labels:
      traefik.enable: 'true'
      traefik.http.services.esp.loadbalancer.server.port: '6052'

  uisp:
    image: nico640/docker-unms:1.4.8
    ports:
      - target: 2055
        published: 2055
        protocol: 'udp'
        mode: 'host'
    environment:
      - TZ=$TZ
      - QUIET_MODE=1
    volumes:
      - uisp:/config
    labels:
      traefik.enable: 'true'
      traefik.http.services.unms.loadbalancer.server.port: 443
      traefik.http.services.unms.loadbalancer.server.scheme: 'https'

volumes:
  tailz:
  certz:
  restore:
  esp:
  uisp:

secrets:
  tailscale_auth_key:
    external: true
  cloudflare_api_token:
    external: true
