FROM	vault

COPY	configZ /configZ/
COPY	proxZ /configZ/proxZ/	
COPY	secretZ /configZ/secretZ/
COPY	codeZ /configZ/codeZ/
COPY	tailZ /configZ/tailZ/

RUN	apk add curl bash jq

ENTRYPOINT [ "/configZ/secretZ/entry.sh" ]
