version: '3.8'

services:
  portainer:
    image: portainer/portainer-ee:alpine
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
